# The desired user display name
current_user: 'User'

# Display name for LLM responses
assistant_name: 'Assistant'

# Host name and port of the frontend and management server
control_host: 'localhost'
control_port: 8080

# datapath will be created by Eternal to host persistent data
data_path: '/Users/$USER/.eternal'

# Service hosts for specific functionalities
service_hosts:
  # generate embeddings and local retrieval services
  retrieval:
    retrieval_host_1:
      host: 'localhost'
      port: 8081
  # image generation and processing
  image:
    image_host_1:
      host: 'localhost'
      port: 8082
  # text-to-speech and speech-to-text    
  speech:
    speech_host_1:
      host: 'localhost'
      port: 8083
  # llm text generation services
  llm:
    llm_host_1:
      host: 'localhost'
      port: '8081'

# OpenAI API Key
oai_key: 'sk-...'

language_models:
  - name: 'openai-gpt'
    homepage: 'https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo'
    prompt: 'Below is an instruction that describes a task. Write a response that appropriately completes the request using advanced AI capabilities.\n### Instruction:\n You are an advanced AI assistant.\n{prompt}\n### Response:'
    ctx: 128000
    roles:
      - 'all'
  - name: 'dolphin-phi2'
    homepage: 'https://huggingface.co/cognitivecomputations/dolphin-2_6-phi-2'
    gguf: 'https://huggingface.co/TheBloke/dolphin-2_6-phi-2-GGUF'
    downloads:
      - 'https://huggingface.co/TheBloke/dolphin-2_6-phi-2-GGUF/resolve/main/dolphin-2_6-phi-2.Q8_0.gguf'
    prompt: "<|im_start|>system{system_message}<|im_end|><|im_start|>user{prompt}<|im_end|><|im_start|>assistant"
    ctx: 16384
    roles:
      - 'chat'
    tags:
      - '7B'
  - name: 'zephyr-7b-beta'
    homepage: 'https://huggingface.co/HuggingFaceH4/zephyr-7b-beta'
    gguf: 'https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF'
    downloads:
      - 'https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF/resolve/main/zephyr-7b-beta.Q4_0.gguf'
    prompt: "<|system|>\n</s>\n<|user|>\n{prompt}</s>\n<|assistant|>"
    ctx: 8192
    roles:
      - 'chat'
    tags:
      - '7B'
  - name: 'codeninja-7b'
    homepage: 'https://huggingface.co/beowolx/CodeNinja-1.0-OpenChat-7B'
    gguf: 'https://huggingface.co/TheBloke/CodeNinja-1.0-OpenChat-7B-GGUF'
    downloads:
      - 'https://huggingface.co/TheBloke/CodeNinja-1.0-OpenChat-7B-GGUF/resolve/main/codeninja-1.0-openchat-7b.Q4_0.gguf'
    prompt: "GPT4 Correct User: {prompt} Respond to the previous information only with concise answers and get straight to the point. You only respond with one code block if necessary. All code examples are complete and ready to run with a main method or function in addition to any other necessary code. Do not deviate from any instructions given.<|end_of_turn|>GPT4 Correct Assistant:"
    ctx: 8192
    roles:
      - 'code'
    tags:
      - '7B'
  - name: 'wizardmath-7b'
    homepage: 'https://huggingface.co/WizardLM/WizardMath-7B-V1.1'
    gguf: 'https://huggingface.co/TheBloke/WizardMath-7B-V1.1-GGUF'
    downloads:
      - 'https://huggingface.co/TheBloke/WizardMath-7B-V1.1-GGUF/resolve/main/wizardmath-7b-v1.1.Q4_0.gguf'
    prompt: "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{prompt}\n\n### Response:"
    ctx: 32768
    roles:
      - 'math'
      - 'logic'
    tags:
      - '7B'
  - name: 'mixtral-8x7b-instruct'
    homepage: 'https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1'
    gguf: 'https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF'
    downloads:
      - 'https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/resolve/main/mixtral-8x7b-instruct-v0.1.Q4_0.gguf'
    prompt:  "[INST] {prompt} [/INST]"
    ctx: 4096
    roles:
      - 'all'
    tags:
      - '8x7B'

image_models:
  - name: 'dreamshaper-8-sd15'
    homepage: 'https://huggingface.co/Lykon/dreamshaper-8'
    downloads:
      - 'https://civitai.com/api/download/models/128713'
