# The desired user display name
current_user: 'User'

# Display name for LLM responses
assistant_name: 'Assistant'

# Host name and port of the frontend and management server
control_host: 'localhost'
control_port: 8080

# datapath will be created by Eternal to host persistent data
data_path: '/Users/$USER/.eternal'

# Service hosts for specific functionalities
service_hosts:
  # generate embeddings and local retrieval services
  retrieval:
    retrieval_host_1:
      host: 'localhost'
      port: 8080
  # image generation and processing
  image:
    image_host_1:
      host: 'localhost'
      port: 8080
  # text-to-speech and speech-to-text    
  speech:
    speech_host_1:
      host: 'localhost'
      port: 8080
  # llm text generation services
  llm:
    llm_host_1:
      host: 'localhost'
      port: '8080'
    llm_host_2:
      host: 'localhost'
      port: '8080'

# OpenAI API Key
oai_key: 'sk-...'

# Anthropic Key for Claude Completions
anthropic_key: 'sk-...'

# Google API Key for Gemini Completions
google_key: 'AI...'

language_models:
  - name: 'openai-gpt'
    homepage: 'https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo'
    prompt: '{system}\n\n{prompt}'
    ctx: 128000
    roles:
      - 'all'
  - name: 'google-gemini-1.5'
    homepage: 'https://deepmind.google/technologies/gemini/#gemini-1.5'
    prompt: '{prompt}'
    ctx: 500000
    roles:
      - 'all'
  - name: 'anthropic-claude-opus'
    homepage: 'https://www.anthropic.com/product'
    prompt: |
      Below is an instruction that describes a task. Write a response that appropriately completes the request using advanced AI capabilities.

      ### Instruction:
      {system}
      {prompt}

      ### Response:
    ctx: 128000
    roles:
      - 'all'
  - name: 'starling-7b-beta'
    homepage: 'https://huggingface.co/HuggingFaceH4/zephyr-7b-beta'
    gguf: 'https://huggingface.co/LoneStriker/Starling-LM-7B-beta-GGUF'
    downloads:
      - 'https://huggingface.co/LoneStriker/Starling-LM-7B-beta-GGUF/resolve/main/Starling-LM-7B-beta-Q8_0.gguf'
    prompt: "Code User: {prompt}<|end_of_turn|>Code Assistant:"
    ctx: 8192
    roles:
      - 'chat'
    tags:
      - '7B'
  - name: 'llama3-8b-instruct'
    homepage: 'https://ai.meta.com/blog/meta-llama-3/'
    gguf: 'https://huggingface.co/bartowski/Meta-Llama-3-8B-Instruct-GGUF'
    downloads:
      - 'https://huggingface.co/bartowski/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct-Q8_0.gguf'
    prompt: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>"
    ctx: 40960
    roles:
      - 'instruct'
    tags:
      - '8B'
  - name: 'llama3-8b-1048k'
    homepage: 'https://ai.meta.com/blog/meta-llama-3/'
    gguf: 'https://huggingface.co/bartowski/Llama-3-8B-Instruct-Gradient-1048k-GGUF'
    downloads:
      - 'https://huggingface.co/bartowski/Llama-3-8B-Instruct-Gradient-1048k-GGUF/resolve/main/Llama-3-8B-Instruct-Gradient-1048k-Q8_0.gguf'
    prompt: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>"
    ctx: 120000
    roles:
      - 'instruct'
    tags:
      - '8B'
  - name: 'llama3-70b-instruct'
    homepage: 'https://ai.meta.com/blog/meta-llama-3/'
    gguf: 'https://huggingface.co/LoneStriker/Meta-Llama-3-70B-Instruct-GGUF'
    downloads:
      - 'https://huggingface.co/LoneStriker/Meta-Llama-3-70B-Instruct-GGUF/resolve/main/Meta-Llama-3-70B-Instruct-Q6_K.gguf'
    prompt: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>"
    ctx: 40960
    roles:
      - 'instruct'
    tags:
      - '70B'
  - name: 'wizardlm-2-7b'
    homepage: 'https://huggingface.co/microsoft/WizardLM-2-7B'
    gguf: 'https://huggingface.co/MaziyarPanahi/WizardLM-2-7B-GGUF'
    downloads:
      - 'https://huggingface.co/MaziyarPanahi/WizardLM-2-7B-GGUF/resolve/main/WizardLM-2-7B.Q8_0.gguf'
    prompt: "<|im_start|>system {system}<|im_end|><|im_start|>user{prompt}<|im_end|><|im_start|>assistant"
    ctx: 32768
    roles:
      - 'all'
    tags:
      - '7b'
  - name: 'wizardlm-2-8x22b'
    homepage: 'https://huggingface.co/microsoft/WizardLM-2-7B'
    gguf: 'https://huggingface.co/MaziyarPanahi/WizardLM-2-8x22B-GGUF'
    downloads:
      - 'https://huggingface.co/MaziyarPanahi/WizardLM-2-8x22B-GGUF/resolve/main/WizardLM-2-8x22B.Q4_K_S-00001-of-00005.gguf'
    prompt: "<|im_start|>system {system}<|im_end|><|im_start|>user{prompt}<|im_end|><|im_start|>assistant"
    ctx: 32768
    roles:
      - 'all'
    tags:
      - '22x7b'
  - name: 'codeninja-7b'
    homepage: 'https://huggingface.co/beowolx/CodeNinja-1.0-OpenChat-7B'
    gguf: 'https://huggingface.co/TheBloke/CodeNinja-1.0-OpenChat-7B-GGUF'
    downloads:
      - 'https://huggingface.co/TheBloke/CodeNinja-1.0-OpenChat-7B-GGUF/resolve/main/codeninja-1.0-openchat-7b.Q8_0.gguf'
    prompt: "GPT4 Correct User: {prompt}<|end_of_turn|>GPT4 Correct Assistant:"
    ctx: 8192
    roles:
      - 'code'
    tags:
      - '7B'
  - name: 'wizardmath-7b'
    homepage: 'https://huggingface.co/WizardLM/WizardMath-7B-V1.1'
    gguf: 'https://huggingface.co/TheBloke/WizardMath-7B-V1.1-GGUF'
    downloads:
      - 'https://huggingface.co/TheBloke/WizardMath-7B-V1.1-GGUF/resolve/main/wizardmath-7b-v1.1.Q8_0.gguf'
    prompt: "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{prompt}\n\n### Response:"
    ctx: 32768
    roles:
      - 'math'
      - 'logic'
    tags:
      - '7B'
  - name: 'mixtral-8x7b-instruct'
    homepage: 'https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1'
    gguf: 'https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF'
    downloads:
      - 'https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/resolve/main/mixtral-8x7b-instruct-v0.1.Q8_0.gguf'
    prompt: "</s>[INST] {system} {prompt} [/INST]"
    ctx: 32768
    roles:
      - 'all'
    tags:
      - '8x7B'
  - name: 'yarn-mistral-7b-64k'
    homepage: 'https://huggingface.co/MaziyarPanahi/Yarn-Mistral-7b-64k-Mistral-7B-Instruct-v0.1'
    gguf: 'https://huggingface.co/MaziyarPanahi/Yarn-Mistral-7b-64k-Mistral-7B-Instruct-v0.1-GGUF'
    downloads:
      - 'https://huggingface.co/MaziyarPanahi/Yarn-Mistral-7b-64k-Mistral-7B-Instruct-v0.1-GGUF/resolve/main/Yarn-Mistral-7b-64k-Mistral-7B-Instruct-v0.1.Q6_K.gguf'
    prompt: "<|prompter|>{prompt}</s><|assistant|>"
    ctx: 64000
    roles:
      - 'all'
    tags:
      - '8x7b'
  - name: 'aixcoder-7b'
    homepage: 'https://huggingface.co/aiXcoder/aixcoder-7b-base'
    gguf: 'https://huggingface.co/bartowski/aixcoder-7b-base-GGUF'
    downloads:
      - 'hhttps://huggingface.co/bartowski/aixcoder-7b-base-GGUF/resolve/main/aixcoder-7b-base-Q8_0.gguf'
    prompt: "{prompt}"
    ctx: 8092
    roles:
      - 'all'
    tags:
      - '7b'
  - name: 'everyone-coder-33b'
    homepage: 'https://huggingface.co/rombodawg/Everyone-Coder-33b-Base'
    gguf: 'https://huggingface.co/TheBloke/Everyone-Coder-33B-Base-GGUF'
    downloads:
      - 'https://huggingface.co/TheBloke/Everyone-Coder-33B-Base-GGUF/resolve/main/everyone-coder-33b-base.Q8_0.gguf'
    prompt: "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n### Instruction:\n{prompt}\n### Response:"
    ctx: 16384
    roles:
      - 'code'
    tags:
      - '33B'
  - name: 'miqu-1-70b'
    homepage: 'https://huggingface.co/miqudev/miqu-1-70b'
    gguf: 'https://huggingface.co/miqudev/miqu-1-70b'
    downloads:
      - 'https://huggingface.co/miqudev/miqu-1-70b/resolve/main/miqu-1-70b.q5_K_M.gguf'
    prompt:  "<s> [INST] {{prompt}} [/INST] ANSWER_1</s>"
    ctx: 32768
    roles:
      - 'all'
    tags:
      - '70B'
  - name: 'llama-8b-hermes'
    homepage: 'https://huggingface.co/NousResearch/Hermes-2-Pro-Llama-3-8B-GGUF'
    gguf: 'https://huggingface.co/NousResearch/Hermes-2-Pro-Llama-3-8B-GGUF'
    downloads:
      - 'https://huggingface.co/NousResearch/Hermes-2-Pro-Llama-3-8B-GGUF/resolve/main/Hermes-2-Pro-Llama-3-8B-Q8_0.gguf'
    prompt:  "<|im_start|>system {system}<|im_end|><|im_start|>user{prompt}<|im_end|><|im_start|>assistant"
    ctx: 8096
    roles:
      - 'all'
    tags:
      - '70B'


image_models:
  - name: 'dreamshaper-8-turbo-sdxl'
    homepage: 'https://huggingface.co/Lykon/dreamshaper-xl-v2-turbo/'
    downloads:
      - 'https://huggingface.co/Lykon/dreamshaper-xl-v2-turbo/resolve/main/DreamShaperXL_Turbo_V2-SFW.safetensors'