# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import TextGeneration_pb2 as TextGeneration__pb2


class TextGeneratorStub(object):
    """The text generation service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateTextStream = channel.unary_stream(
                '/textgenerator.TextGenerator/GenerateTextStream',
                request_serializer=TextGeneration__pb2.TextRequest.SerializeToString,
                response_deserializer=TextGeneration__pb2.TextResponse.FromString,
                )


class TextGeneratorServicer(object):
    """The text generation service definition.
    """

    def GenerateTextStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextGeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateTextStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateTextStream,
                    request_deserializer=TextGeneration__pb2.TextRequest.FromString,
                    response_serializer=TextGeneration__pb2.TextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'textgenerator.TextGenerator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextGenerator(object):
    """The text generation service definition.
    """

    @staticmethod
    def GenerateTextStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/textgenerator.TextGenerator/GenerateTextStream',
            TextGeneration__pb2.TextRequest.SerializeToString,
            TextGeneration__pb2.TextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
