# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TextGeneration.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14TextGeneration.proto\x12\rtextgenerator\"\x1d\n\x0bTextRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\" \n\x0cTextResponse\x12\x10\n\x08response\x18\x01 \x01(\t2`\n\rTextGenerator\x12O\n\x12GenerateTextStream\x12\x1a.textgenerator.TextRequest\x1a\x1b.textgenerator.TextResponse0\x01\x42\nZ\x08./eprotob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TextGeneration_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010./eproto'
  _globals['_TEXTREQUEST']._serialized_start=39
  _globals['_TEXTREQUEST']._serialized_end=68
  _globals['_TEXTRESPONSE']._serialized_start=70
  _globals['_TEXTRESPONSE']._serialized_end=102
  _globals['_TEXTGENERATOR']._serialized_start=104
  _globals['_TEXTGENERATOR']._serialized_end=200
# @@protoc_insertion_point(module_scope)
